version: '1.0'

services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    depends_on:
      - db
    ports:
      - 8081:8080
    networks:
      - app-net
      - data-net

  frontend:
    build: 
      context: ..
      dockerfile: frontend/Dockerfile
    environment:
      - PUBLIC_BACKEND_URL="http://localhost:8081"
    ports:
      - 3000:3000
    networks:
      - app-net

  db:
    container_name: postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shoppingdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - data-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  app-net:
  data-net: