# Go-Image für devconatiner
FROM mcr.microsoft.com/devcontainers/go AS builder

RUN sudo apt-get update && sudo apt upgrade && sudo apt-get install -y nodejs npm && sudo apt-get install -y docker.io

RUN npm install -g svelte@latest
