apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  containers:
  - name: frontend
    image: ghcr.io/01bap/distributedsystems/itemshop-frontend:latest
    ports:
    - containerPort: 3000
    # env:
    # - name: VITE_PUBLIC_BACKEND_URL
    #   value: "http://localhost:8080"