apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    app.kubernetes.io/name: db
spec:
  containers:
  - name: db
    image: postgres:15
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: shoppingdb
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-data
    emptyDir: {}