name: Docker Image Publishing

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'    
            
permissions:
    packages: write # Allows action to publish packages

env:
    REGISTRY: ghcr.io
    REPOSITORY: ${{github.repository}}
    IMAGE_NAME_FRONTEND: itemshop-frontend
    FRONTEND_TAG: latest
    IMAGE_NAME_BACKEND: itemshop-backend
    BACKEND_TAG: latest

jobs:
    frontend-image-publishing:
        runs-on: ubuntu-latest
        #container:
        #    image:
        #        
        #    credentials:
        #        username: ${{ github.actor }}
        #        password: ${{ secrets.github_token }}
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Building image
              run: docker build -t $IMAGE_NAME_FRONTEND ./frontend
  
            - name: Pushing image
              run: docker push $REGISTRY/$REPOSITORY/$IMAGE_NAME_FRONTEND:$FRONTEND_TAG
    
    backend-image-publishing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Building image
              run: docker build -t $IMAGE_NAME_BACKEND ./backend

            - name: Pushing image
              run: docker push $REGISTRY/$REPOSITORY/$IMAGE_NAME_BACKEND:$BACKEND_TAG